runtime: python36
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: Flask
  version: 1.03
- name: google-api-core
  version: 1.23.0
- name: google-api-python-client
  version: 1.12.5
- name: numpy
  version: 1.18.1
- name: Pillow
  version: 7.1.0
